name: atan_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  cloud_firestore: ^4.3.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.6
  firebase_core: ^2.5.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  get: 4.6.5
  google_sign_in: ^5.4.4
  hexcolor: ^3.0.1
  icons_plus: ^4.0.0
  phosphor_flutter: ^1.4.0
  sizer: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  uses-material-design: true
